// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Hypar.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace FastProjectToTopography
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v13.0.0.0)")]
    
    public  class FastProjectToTopographyInputs : ArgsBase
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public FastProjectToTopographyInputs(IList<Polygon> @polygons, double @rayDensity, bool @useG3, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<FastProjectToTopographyInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @polygons, @rayDensity, @useG3});
            }
        
            this.Polygons = @polygons;
            this.RayDensity = @rayDensity;
            this.UseG3 = @useG3;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        [Newtonsoft.Json.JsonProperty("Polygons", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Polygon> Polygons { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Ray Density", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double RayDensity { get; set; } = 1D;
    
        [Newtonsoft.Json.JsonProperty("Use G3", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool UseG3 { get; set; } = true;
    
    }
}